#!/bin/zsh

echo "starting setting up antlr env"
export CLASSPATH=".:/usr/local/lib/antlr-4.8-complete.jar:$CLASSPATH"
alias antlr4="java -jar /usr/local/lib/antlr-4.8-complete.jar"
alias grun="java org.antlr.v4.gui.TestRig"
echo "successfully setup antlr env"

